#!/usr/bin/env python3
"""Fuse include/nsig/*.hpp into single_include/nsig.hpp.

Local `#include "..."` directives are inlined once in dependency order; system
includes are hoisted to the top and de-duplicated.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "include" / "nsig"
OUT = ROOT / "single_include" / "nsig.hpp"

ORDER = ["core.hpp", "signals.hpp", "static_graph.hpp", "expr.hpp", "adapt.hpp", "async.hpp"]

SYSTEM_INCLUDE = re.compile(r'^\s*#\s*include\s*<([^>]+)>\s*$')
LOCAL_INCLUDE = re.compile(r'^\s*#\s*include\s*"([^"]+)"\s*$')
PRAGMA_ONCE = re.compile(r'^\s*#\s*pragma\s+once\s*$')


def main() -> int:
    system: list[str] = []
    seen: set[str] = set()
    body: list[str] = []

    for name in ORDER:
        path = SRC / name
        body.append(f"\n// ===== {name} " + "=" * (66 - len(name)) + "\n")
        for line in path.read_text().splitlines():
            if PRAGMA_ONCE.match(line) or LOCAL_INCLUDE.match(line):
                continue
            m = SYSTEM_INCLUDE.match(line)
            if m:
                if m.group(1) not in seen:
                    seen.add(m.group(1))
                    system.append(f"#include <{m.group(1)}>")
                continue
            body.append(line)

    version = (SRC / "nsig.hpp").read_text()
    macros = "\n".join(
        l for l in version.splitlines() if l.startswith("#define NSIG_VERSION")
    )

    header = [
        "// native-signals — single-header amalgamation.",
        "// Generated by tools/amalgamate.py; edit include/nsig/*.hpp instead.",
        "//",
        "// Reactive programming suite for modern C++ (C++23).",
        "// Algorithm ported from https://github.com/stackblitz/alien-signals (MIT).",
        "#pragma once",
        "",
        macros,
        "",
        *sorted(system),
        "",
    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(header) + "\n".join(body) + "\n")
    lines = OUT.read_text().count("\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({lines} lines, {OUT.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
